POST http://localhost:8080/complaints
Content-Type: application/json

{
  "userId" : "foo@bar.com",
  "topic"  : "Testing",
  "message": "Just testing the API"
}

###

GET http://localhost:8080/complaints

###

GET http://localhost:8080/complaints/ea9a1e5e-19a9-4bf4-93d4-20de05495d22

###